# Generated by Django 5.2.8 on 2025-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Health Centre', 'Health Centre'), ('Dispensary', 'Dispensary'), ('Clinic', 'Clinic'), ('Pharmacy', 'Pharmacy'), ('Laboratory', 'Laboratory'), ('Maternity', 'Maternity')], max_length=50)),
                ('level', models.CharField(choices=[('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5')], max_length=10)),
                ('has_emergency', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('services', models.ManyToManyField(blank=True, to='medapp.service')),
            ],
        ),
    ]
