# Generated by Django 5.2.8 on 2025-12-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_facility_created_at_facility_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
    ]
