# Generated by Django 5.2.8 on 2025-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_alter_facility_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.CharField(blank=True, help_text='Image filename or URL (ImageField disabled for portability)', max_length=255, null=True),
        ),
    ]
